GET http://localhost:3000

###
GET http://localhost:3000/abc

###
POST http://localhost:3000/user/login

###
POST http://localhost:3000/user/register
Content-Type: application/json

{
  "email" : "miNJ9@gmail...com",
  "password" : "12345678"
}

###
POST http://localhost:3000/user/logout
###
POST http://localhost:3000/user/refresh-token